---
# This is based on a nice explanation here: 
# https://serversforhackers.com/c/automatic-security-updates-centos

- name: Install yum-cron
  package: name=yum-cron state=present
  tags: [auto-updates]
  when: centos7

- name: Enable yum-cron
  service: name=yum-cron state=started enabled=yes
  tags: [auto-updates]
  when: centos7

- name: Update yum-cron template
  template: src=yum-cron.conf.j2 dest=/etc/yum/yum-cron.conf
  tags: [auto-updates]
  when: centos7

- name: dnf-automatic | Install
  package: name=dnf-automatic state=present
  tags: [auto-updates]
  when: centos8

- name: dnf-automaticc | Configure
  template: src=dnf-automatic.conf.j2 dest=/etc/dnf/automatic.conf
  tags: [auto-updates]
  when: centos8

- name: dnf-automatic | Enable, Start
  service: name=dnf-automatic state=started enabled=yes
  tags: [auto-updates]
  when: centos8
