---
- name: Write public service def
  template: src=firewalld.conf.j2 dest=/etc/firewalld/firewalld.conf
  register: firewalld_conf

- name: Write public service def
  template: src=firewalld-public.xml.j2 dest=/etc/firewalld/zones/public.xml
  register: firewalld_conf

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: Reload firewalld
  service: name=firewalld state=reloaded enabled=yes
  when: firewalld_conf.changed
