---
- name: Install firewalld
  package: name=firewalld state=present
  tags: [firewalld]

- name: Write firewalld.conf
  template: src=firewalld.conf.j2 dest=/etc/firewalld/firewalld.conf
  notify: [Reload firewalld]
  tags: [firewalld]

- name: Write public zone def
  template: src=firewalld-public.xml.j2 dest=/etc/firewalld/zones/public.xml
  notify: [Reload firewalld]
  tags: [firewalld]

- name: Start firewalld
  service: name=firewalld state=started enabled=yes
  tags: [firewalld]

