---
- name: Check we aren't using root to provision
  shell: printenv SUDO_USER
  register: sudo_user
  changed_when: false
  failed_when: sudo_user.stdout == '' or sudo_user.stdout == 'root'
  tags: [ssh, check]

- name: Disallow root login via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?\\w*PermitRootLogin"
    line: "PermitRootLogin no"
  register: sshd_config
  notify: [Reload sshd]
  tags: [ssh]
